### ISSUE TITLE
doesn't work with html5 - <!DOCTYPE html>

### ISSUE THREAD

**Issue by iateadonut** [asvd/dragscroll#24] opened 2016-10-26 14:43 UTC
Works fine with just <html> at the top of a file.
No longer works when using <!DOCTYPE html> instead.

Demo here:
http://100wires.com/dragscroll/index1.html
http://100wires.com/dragscroll/index3.html

The only difference between the two is the first line, <html> or <!DOCTYPE html>

**Comment by iateadonut** [comment] 2016-10-26 15:28
tested on chrome and it works there.  only doesn't work on firefox.

**Comment by asvd** [comment] 2016-10-26 17:18
ok, reproduced, thanks for the feedback...

**Comment by asvd** [comment] 2016-10-26 18:45
I cannot reproduce the issue on http://asvd.github.io/dragscroll/index.html

It also has the specified doctype, but it works. Can you provide simplier example, i.e. without the additional libs included? For now it seems like they break the dragscroll somehow only if the doctype is specified

**Comment by iateadonut** [comment] 2016-10-27 00:48
I've taken out everything possible:
http://100wires.com/dragscroll/
http://100wires.com/dragscroll/index4.html

**Comment by asvd** [comment] 2016-10-27 21:26
http://stackoverflow.com/questions/5769148/scrolltop-and-doctype

This is the reason, will prepare a fix soon

**Comment by asvd** [comment] 2016-10-27 22:18
Fixed in [v0.0.7](https://github.com/asvd/dragscroll/releases/tag/v0.0.7)

**Closed by asvd** 2016-10-27 22:18 UTC
